Database:
  Type: sqlite # pgsql, sqlite, mysql
  Host: localhost
  Port: 5432
  Name: dominion
  User: dominion
  Pass: dominion

Language: zh-cn

AutoCreateRadius: 10

Limit:
  SpawnProtection: 10
  MinY: -64
  MaxY: 320
  SizeX: 128
  SizeY: 64
  SizeZ: 128
  Amount: 10
  Depth: 3
  Vert: false
  WorldBlackList: ['some_world']
  OpByPass: true

Teleport:
  Enable: true
  Delay: 0
  CoolDown: 0

AutoCleanAfterDays: 180

Tool: ARROW

Economy:
  Enable: false
  Price: 10.0
  OnlyXZ: false
  Refund: 0.85

FlyPermissionNodes:
  - essentials.fly
  - cmi.command.fly

ResidenceMigration: false

GroupTitle:
  Enable: false
  Prefix: "["
  Suffix: "]"

BlueMap: false
Dynmap: false

CheckUpdate: true

Debug: false

Timer: false